# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: GH Release
      # You may pin to the exact commit or the version.
      # uses: softprops/action-gh-release@b7e450da2a4b4cb4bfbae528f788167786cfcedf
      uses: softprops/action-gh-release@v0.1.5
    - name: GH Pages deploy
      # You may pin to the exact commit or the version.
      # uses: Cecilapp/GitHub-Pages-deploy@10c15d01fe8f5100fdcc07f1568fe94bfa7b7d4c
      uses: Cecilapp/GitHub-Pages-deploy@2.0.1
